var searchData=
[
  ['randomdatagenerator_10802',['RandomDataGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomDataGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomdatageneratorprogram_10803',['RandomDataGeneratorProgram',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomDataGeneratorProgram.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomdatageneratorsettings_10804',['RandomDataGeneratorSettings',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomDataGeneratorSettings.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randompricegenerator_10805',['RandomPriceGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomPriceGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomvaluegenerator_10806',['RandomValueGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomValueGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['randomvaluegeneratorexception_10807',['RandomValueGeneratorException',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1RandomValueGeneratorException.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['rangebar_10808',['RangeBar',['../classQuantConnect_1_1Data_1_1Market_1_1RangeBar.html',1,'QuantConnect::Data::Market']]],
  ['rangeconsolidator_10809',['RangeConsolidator',['../classQuantConnect_1_1Data_1_1Consolidators_1_1RangeConsolidator.html',1,'QuantConnect::Data::Consolidators']]],
  ['rategate_10810',['RateGate',['../classQuantConnect_1_1Util_1_1RateGate.html',1,'QuantConnect::Util']]],
  ['ratelimitenumerator_10811',['RateLimitEnumerator',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Enumerators_1_1RateLimitEnumerator.html',1,'QuantConnect::Lean::Engine::DataFeeds::Enumerators']]],
  ['rateofchange_10812',['RateOfChange',['../classQuantConnect_1_1Indicators_1_1RateOfChange.html',1,'QuantConnect::Indicators']]],
  ['rateofchangepercent_10813',['RateOfChangePercent',['../classQuantConnect_1_1Indicators_1_1RateOfChangePercent.html',1,'QuantConnect::Indicators']]],
  ['rateofchangeratio_10814',['RateOfChangeRatio',['../classQuantConnect_1_1Indicators_1_1RateOfChangeRatio.html',1,'QuantConnect::Indicators']]],
  ['rawfileprocessor_10815',['RawFileProcessor',['../classQuantConnect_1_1ToolBox_1_1RawFileProcessor.html',1,'QuantConnect::ToolBox']]],
  ['rawmaterialsbalancesheet_10816',['RawMaterialsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RawMaterialsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['rbibrokeragemodel_10817',['RBIBrokerageModel',['../classQuantConnect_1_1Brokerages_1_1RBIBrokerageModel.html',1,'QuantConnect.Brokerages.RBIBrokerageModel'],['../classQuantConnect_1_1Messages_1_1RBIBrokerageModel.html',1,'QuantConnect.Messages.RBIBrokerageModel']]],
  ['rbifeemodel_10818',['RBIFeeModel',['../classQuantConnect_1_1Orders_1_1Fees_1_1RBIFeeModel.html',1,'QuantConnect::Orders::Fees']]],
  ['rbiorderproperties_10819',['RBIOrderProperties',['../classQuantConnect_1_1Orders_1_1RBIOrderProperties.html',1,'QuantConnect::Orders']]],
  ['readchartresponse_10820',['ReadChartResponse',['../classQuantConnect_1_1Api_1_1ReadChartResponse.html',1,'QuantConnect::Api']]],
  ['readererrordetectedeventargs_10821',['ReaderErrorDetectedEventArgs',['../classQuantConnect_1_1ReaderErrorDetectedEventArgs.html',1,'QuantConnect']]],
  ['readererroreventargs_10822',['ReaderErrorEventArgs',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1ReaderErrorEventArgs.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['readerwriterlockslimextensions_10823',['ReaderWriterLockSlimExtensions',['../classQuantConnect_1_1Util_1_1ReaderWriterLockSlimExtensions.html',1,'QuantConnect::Util']]],
  ['readonlysecurityvaluescollection_10824',['ReadOnlySecurityValuesCollection',['../classQuantConnect_1_1Messages_1_1ReadOnlySecurityValuesCollection.html',1,'QuantConnect::Messages']]],
  ['readordersresponsejsonconverter_10825',['ReadOrdersResponseJsonConverter',['../classQuantConnect_1_1Orders_1_1ReadOrdersResponseJsonConverter.html',1,'QuantConnect::Orders']]],
  ['realizedgainlossonsaleofloansandleasecashflowstatement_10826',['RealizedGainLossOnSaleOfLoansAndLeaseCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RealizedGainLossOnSaleOfLoansAndLeaseCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['realtimeprovider_10827',['RealTimeProvider',['../classQuantConnect_1_1RealTimeProvider.html',1,'QuantConnect']]],
  ['realtimescheduleeventservice_10828',['RealTimeScheduleEventService',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1RealTimeScheduleEventService.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['realtimesynchronizedtimer_10829',['RealTimeSynchronizedTimer',['../classQuantConnect_1_1RealTimeSynchronizedTimer.html',1,'QuantConnect']]],
  ['receiptsfromcustomerscashflowstatement_10830',['ReceiptsfromCustomersCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceiptsfromCustomersCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['receiptsfromgovernmentgrantscashflowstatement_10831',['ReceiptsfromGovernmentGrantsCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceiptsfromGovernmentGrantsCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['receivablesadjustmentsallowancesbalancesheet_10832',['ReceivablesAdjustmentsAllowancesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceivablesAdjustmentsAllowancesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['receivablesbalancesheet_10833',['ReceivablesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceivablesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['receivableturnover_10834',['ReceivableTurnover',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReceivableTurnover.html',1,'QuantConnect::Data::Fundamental']]],
  ['reconciledcostofrevenueincomestatement_10835',['ReconciledCostOfRevenueIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReconciledCostOfRevenueIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reconcileddepreciationincomestatement_10836',['ReconciledDepreciationIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReconciledDepreciationIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['ref_10837',['Ref',['../classQuantConnect_1_1Util_1_1Ref.html',1,'QuantConnect::Util']]],
  ['ref_3c_20timespan_20_3e_10838',['Ref&lt; TimeSpan &gt;',['../classQuantConnect_1_1Util_1_1Ref.html',1,'QuantConnect::Util']]],
  ['referencewrapper_10839',['ReferenceWrapper',['../classQuantConnect_1_1Util_1_1ReferenceWrapper.html',1,'QuantConnect::Util']]],
  ['referencewrapper_3c_20datetime_20_3e_10840',['ReferenceWrapper&lt; DateTime &gt;',['../classQuantConnect_1_1Util_1_1ReferenceWrapper.html',1,'QuantConnect::Util']]],
  ['referencewrapper_3c_20decimal_20_3e_10841',['ReferenceWrapper&lt; decimal &gt;',['../classQuantConnect_1_1Util_1_1ReferenceWrapper.html',1,'QuantConnect::Util']]],
  ['refreshenumerator_10842',['RefreshEnumerator',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Enumerators_1_1RefreshEnumerator.html',1,'QuantConnect::Lean::Engine::DataFeeds::Enumerators']]],
  ['registeredsecuritydatatypesprovider_10843',['RegisteredSecurityDataTypesProvider',['../classQuantConnect_1_1Securities_1_1RegisteredSecurityDataTypesProvider.html',1,'QuantConnect.Securities.RegisteredSecurityDataTypesProvider'],['../classQuantConnect_1_1Messages_1_1RegisteredSecurityDataTypesProvider.html',1,'QuantConnect.Messages.RegisteredSecurityDataTypesProvider']]],
  ['regressionchannel_10844',['RegressionChannel',['../classQuantConnect_1_1Indicators_1_1RegressionChannel.html',1,'QuantConnect::Indicators']]],
  ['regressionfileloghandler_10845',['RegressionFileLogHandler',['../classQuantConnect_1_1Logging_1_1RegressionFileLogHandler.html',1,'QuantConnect::Logging']]],
  ['regressiongrowthofdividends5years_10846',['RegressionGrowthofDividends5Years',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegressionGrowthofDividends5Years.html',1,'QuantConnect::Data::Fundamental']]],
  ['regressiongrowthoperatingrevenue5years_10847',['RegressionGrowthOperatingRevenue5Years',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegressionGrowthOperatingRevenue5Years.html',1,'QuantConnect::Data::Fundamental']]],
  ['regressionresulthandler_10848',['RegressionResultHandler',['../classQuantConnect_1_1Lean_1_1Engine_1_1Results_1_1RegressionResultHandler.html',1,'QuantConnect::Lean::Engine::Results']]],
  ['regressiontestexception_10849',['RegressionTestException',['../classQuantConnect_1_1RegressionTestException.html',1,'QuantConnect']]],
  ['regularexpression_10850',['RegularExpression',['../classQuantConnect_1_1Util_1_1Validate_1_1RegularExpression.html',1,'QuantConnect::Util::Validate']]],
  ['regulatoryassetsbalancesheet_10851',['RegulatoryAssetsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegulatoryAssetsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['regulatoryliabilitiesbalancesheet_10852',['RegulatoryLiabilitiesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RegulatoryLiabilitiesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsuranceandotherrecoveriesreceivedcashflowstatement_10853',['ReinsuranceandOtherRecoveriesReceivedCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceandOtherRecoveriesReceivedCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsuranceassetsbalancesheet_10854',['ReinsuranceAssetsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceAssetsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancebalancespayablebalancesheet_10855',['ReinsuranceBalancesPayableBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceBalancesPayableBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoverablebalancesheet_10856',['ReinsuranceRecoverableBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoverableBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoveriesclaimsandbenefitsincomestatement_10857',['ReinsuranceRecoveriesClaimsandBenefitsIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoveriesClaimsandBenefitsIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoveriesofinsuranceliabilitiesincomestatement_10858',['ReinsuranceRecoveriesofInsuranceLiabilitiesIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoveriesofInsuranceLiabilitiesIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reinsurancerecoveriesofinvestmentcontractincomestatement_10859',['ReinsuranceRecoveriesofInvestmentContractIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReinsuranceRecoveriesofInvestmentContractIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['relativedailyvolume_10860',['RelativeDailyVolume',['../classQuantConnect_1_1Indicators_1_1RelativeDailyVolume.html',1,'QuantConnect::Indicators']]],
  ['relativemovingaverage_10861',['RelativeMovingAverage',['../classQuantConnect_1_1Indicators_1_1RelativeMovingAverage.html',1,'QuantConnect::Indicators']]],
  ['relativestandarddeviationvolatilitymodel_10862',['RelativeStandardDeviationVolatilityModel',['../classQuantConnect_1_1Securities_1_1RelativeStandardDeviationVolatilityModel.html',1,'QuantConnect::Securities']]],
  ['relativestrengthindex_10863',['RelativeStrengthIndex',['../classQuantConnect_1_1Indicators_1_1RelativeStrengthIndex.html',1,'QuantConnect::Indicators']]],
  ['relativevigorindex_10864',['RelativeVigorIndex',['../classQuantConnect_1_1Indicators_1_1RelativeVigorIndex.html',1,'QuantConnect::Indicators']]],
  ['relativevigorindexsignal_10865',['RelativeVigorIndexSignal',['../classQuantConnect_1_1Indicators_1_1RelativeVigorIndexSignal.html',1,'QuantConnect::Indicators']]],
  ['remotefilesubscriptionstreamreader_10866',['RemoteFileSubscriptionStreamReader',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Transport_1_1RemoteFileSubscriptionStreamReader.html',1,'QuantConnect::Lean::Engine::DataFeeds::Transport']]],
  ['removedmember_10867',['RemovedMember',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1PendingRemovalsManager_1_1RemovedMember.html',1,'QuantConnect::Lean::Engine::DataFeeds::PendingRemovalsManager']]],
  ['renkobar_10868',['RenkoBar',['../classQuantConnect_1_1Data_1_1Market_1_1RenkoBar.html',1,'QuantConnect::Data::Market']]],
  ['renkoconsolidator_10869',['RenkoConsolidator',['../classQuantConnect_1_1Data_1_1Consolidators_1_1RenkoConsolidator.html',1,'QuantConnect.Data.Consolidators.RenkoConsolidator'],['../classQuantConnect_1_1Data_1_1Consolidators_1_1RenkoConsolidator.html',1,'QuantConnect.Data.Consolidators.RenkoConsolidator&lt; TInput &gt;']]],
  ['renkoconsolidator_3c_20t_20_3e_10870',['RenkoConsolidator&lt; T &gt;',['../classQuantConnect_1_1Data_1_1Consolidators_1_1RenkoConsolidator.html',1,'QuantConnect::Data::Consolidators']]],
  ['rentandlandingfeescostofrevenueincomestatement_10871',['RentandLandingFeesCostofRevenueIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RentandLandingFeesCostofRevenueIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['rentandlandingfeesincomestatement_10872',['RentAndLandingFeesIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RentAndLandingFeesIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['rentexpensesupplementalincomestatement_10873',['RentExpenseSupplementalIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RentExpenseSupplementalIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['reorganizationothercostscashflowstatement_10874',['ReorganizationOtherCostsCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReorganizationOtherCostsCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['repaymentinleasefinancingcashflowstatement_10875',['RepaymentInLeaseFinancingCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RepaymentInLeaseFinancingCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['repaymentofdebtcashflowstatement_10876',['RepaymentOfDebtCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RepaymentOfDebtCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['report_10877',['Report',['../classQuantConnect_1_1Report_1_1Report.html',1,'QuantConnect::Report']]],
  ['reportargumentparser_10878',['ReportArgumentParser',['../classQuantConnect_1_1Configuration_1_1ReportArgumentParser.html',1,'QuantConnect::Configuration']]],
  ['reportednormalizedbasiceps_10879',['ReportedNormalizedBasicEPS',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReportedNormalizedBasicEPS.html',1,'QuantConnect::Data::Fundamental']]],
  ['reportednormalizeddilutedeps_10880',['ReportedNormalizedDilutedEPS',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ReportedNormalizedDilutedEPS.html',1,'QuantConnect::Data::Fundamental']]],
  ['reportelement_10881',['ReportElement',['../classQuantConnect_1_1Report_1_1ReportElements_1_1ReportElement.html',1,'QuantConnect::Report::ReportElements']]],
  ['repurchaseofcapitalstockcashflowstatement_10882',['RepurchaseOfCapitalStockCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RepurchaseOfCapitalStockCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['researchanddevelopmentexpensessupplementalincomestatement_10883',['ResearchAndDevelopmentExpensesSupplementalIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ResearchAndDevelopmentExpensesSupplementalIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['researchanddevelopmentincomestatement_10884',['ResearchAndDevelopmentIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ResearchAndDevelopmentIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['researchguide_10885',['ResearchGuide',['../classQuantConnect_1_1Api_1_1ResearchGuide.html',1,'QuantConnect::Api']]],
  ['researchnodepacket_10886',['ResearchNodePacket',['../classQuantConnect_1_1Packets_1_1ResearchNodePacket.html',1,'QuantConnect::Packets']]],
  ['reservedbuyingpowerforposition_10887',['ReservedBuyingPowerForPosition',['../classQuantConnect_1_1Securities_1_1ReservedBuyingPowerForPosition.html',1,'QuantConnect::Securities']]],
  ['reservedbuyingpowerforpositiongroup_10888',['ReservedBuyingPowerForPositionGroup',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerForPositionGroup.html',1,'QuantConnect::Securities::Positions']]],
  ['reservedbuyingpowerforpositiongroupparameters_10889',['ReservedBuyingPowerForPositionGroupParameters',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerForPositionGroupParameters.html',1,'QuantConnect::Securities::Positions']]],
  ['reservedbuyingpowerforpositionparameters_10890',['ReservedBuyingPowerForPositionParameters',['../classQuantConnect_1_1Securities_1_1ReservedBuyingPowerForPositionParameters.html',1,'QuantConnect::Securities']]],
  ['reservedbuyingpowerimpact_10891',['ReservedBuyingPowerImpact',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerImpact.html',1,'QuantConnect::Securities::Positions']]],
  ['reservedbuyingpowerimpactparameters_10892',['ReservedBuyingPowerImpactParameters',['../classQuantConnect_1_1Securities_1_1Positions_1_1ReservedBuyingPowerImpactParameters.html',1,'QuantConnect::Securities::Positions']]],
  ['resetcompositeindicator_10893',['ResetCompositeIndicator',['../classQuantConnect_1_1Indicators_1_1ResetCompositeIndicator.html',1,'QuantConnect::Indicators']]],
  ['restresponse_10894',['RestResponse',['../classQuantConnect_1_1Api_1_1RestResponse.html',1,'QuantConnect::Api']]],
  ['restrictedcashandcashequivalentsbalancesheet_10895',['RestrictedCashAndCashEquivalentsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCashAndCashEquivalentsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedcashandinvestmentsbalancesheet_10896',['RestrictedCashAndInvestmentsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCashAndInvestmentsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedcashbalancesheet_10897',['RestrictedCashBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCashBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedcommonstockbalancesheet_10898',['RestrictedCommonStockBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedCommonStockBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restrictedinvestmentsbalancesheet_10899',['RestrictedInvestmentsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestrictedInvestmentsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['restructuringandmergernacquisitionincomestatement_10900',['RestructuringAndMergernAcquisitionIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RestructuringAndMergernAcquisitionIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['restsubscriptionstreamreader_10901',['RestSubscriptionStreamReader',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Transport_1_1RestSubscriptionStreamReader.html',1,'QuantConnect::Lean::Engine::DataFeeds::Transport']]],
  ['result_10902',['Result',['../classQuantConnect_1_1Result.html',1,'QuantConnect.Result'],['../classQuantConnect_1_1Commands_1_1CancelOrderCommand_1_1Result.html',1,'QuantConnect.Commands.CancelOrderCommand.Result'],['../classQuantConnect_1_1Commands_1_1AddSecurityCommand_1_1Result.html',1,'QuantConnect.Commands.AddSecurityCommand.Result']]],
  ['resulthandlerinitializeparameters_10903',['ResultHandlerInitializeParameters',['../classQuantConnect_1_1Lean_1_1Engine_1_1Results_1_1ResultHandlerInitializeParameters.html',1,'QuantConnect::Lean::Engine::Results']]],
  ['resultsutil_10904',['ResultsUtil',['../classQuantConnect_1_1Report_1_1ResultsUtil.html',1,'QuantConnect::Report']]],
  ['retainedearningsbalancesheet_10905',['RetainedEarningsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RetainedEarningsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['returnssymboldata_10906',['ReturnsSymbolData',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1ReturnsSymbolData.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['returnssymboldataextensions_10907',['ReturnsSymbolDataExtensions',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1ReturnsSymbolDataExtensions.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['revenuegrowth_10908',['RevenueGrowth',['../classQuantConnect_1_1Data_1_1Fundamental_1_1RevenueGrowth.html',1,'QuantConnect::Data::Fundamental']]],
  ['rho_10909',['Rho',['../classQuantConnect_1_1Indicators_1_1Rho.html',1,'QuantConnect::Indicators']]],
  ['rickshawman_10910',['RickshawMan',['../classQuantConnect_1_1Indicators_1_1CandlestickPatterns_1_1RickshawMan.html',1,'QuantConnect::Indicators::CandlestickPatterns']]],
  ['risefallthreemethods_10911',['RiseFallThreeMethods',['../classQuantConnect_1_1Indicators_1_1CandlestickPatterns_1_1RiseFallThreeMethods.html',1,'QuantConnect::Indicators::CandlestickPatterns']]],
  ['riskfreeinterestratemodelextensions_10912',['RiskFreeInterestRateModelExtensions',['../classQuantConnect_1_1Data_1_1RiskFreeInterestRateModelExtensions.html',1,'QuantConnect::Data']]],
  ['riskfreeinterestratemodelpythonwrapper_10913',['RiskFreeInterestRateModelPythonWrapper',['../classQuantConnect_1_1Python_1_1RiskFreeInterestRateModelPythonWrapper.html',1,'QuantConnect::Python']]],
  ['riskmanagementmodel_10914',['RiskManagementModel',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Risk_1_1RiskManagementModel.html',1,'QuantConnect::Algorithm::Framework::Risk']]],
  ['riskmanagementmodelpythonwrapper_10915',['RiskManagementModelPythonWrapper',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Risk_1_1RiskManagementModelPythonWrapper.html',1,'QuantConnect::Algorithm::Framework::Risk']]],
  ['riskparityportfolioconstructionmodel_10916',['RiskParityPortfolioConstructionModel',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1RiskParityPortfolioConstructionModel.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['riskparityportfoliooptimizer_10917',['RiskParityPortfolioOptimizer',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Portfolio_1_1RiskParityPortfolioOptimizer.html',1,'QuantConnect::Algorithm::Framework::Portfolio']]],
  ['roa_10918',['ROA',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROA.html',1,'QuantConnect::Data::Fundamental']]],
  ['roa5yravg_10919',['ROA5YrAvg',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROA5YrAvg.html',1,'QuantConnect::Data::Fundamental']]],
  ['roe_10920',['ROE',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROE.html',1,'QuantConnect::Data::Fundamental']]],
  ['roe5yravg_10921',['ROE5YrAvg',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROE5YrAvg.html',1,'QuantConnect::Data::Fundamental']]],
  ['rogerssatchellvolatility_10922',['RogersSatchellVolatility',['../classQuantConnect_1_1Indicators_1_1RogersSatchellVolatility.html',1,'QuantConnect::Indicators']]],
  ['roic_10923',['ROIC',['../classQuantConnect_1_1Data_1_1Fundamental_1_1ROIC.html',1,'QuantConnect::Data::Fundamental']]],
  ['rolling_10924',['Rolling',['../classQuantConnect_1_1Report_1_1Rolling.html',1,'QuantConnect::Report']]],
  ['rollingwindow_10925',['RollingWindow',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect.Indicators.RollingWindow&lt; T &gt;'],['../classQuantConnect_1_1Messages_1_1RollingWindow.html',1,'QuantConnect.Messages.RollingWindow']]],
  ['rollingwindow_3c_20decimal_20_3e_10926',['RollingWindow&lt; decimal &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20double_20_3e_10927',['RollingWindow&lt; double &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20ibasedatabar_20_3e_10928',['RollingWindow&lt; IBaseDataBar &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20indicatordatapoint_20_3e_10929',['RollingWindow&lt; IndicatorDataPoint &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20quantconnect_3a_3aindicators_3a_3aindicatordatapoint_20_3e_10930',['RollingWindow&lt; QuantConnect::Indicators::IndicatorDataPoint &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rollingwindow_3c_20quantconnect_3a_3aindicators_3a_3apivotpoint_20_3e_10931',['RollingWindow&lt; QuantConnect::Indicators::PivotPoint &gt;',['../classQuantConnect_1_1Indicators_1_1RollingWindow.html',1,'QuantConnect::Indicators']]],
  ['rsialphamodel_10932',['RsiAlphaModel',['../classQuantConnect_1_1Algorithm_1_1Framework_1_1Alphas_1_1RsiAlphaModel.html',1,'QuantConnect::Algorithm::Framework::Alphas']]],
  ['runtimeerrorpacket_10933',['RuntimeErrorPacket',['../classQuantConnect_1_1Packets_1_1RuntimeErrorPacket.html',1,'QuantConnect::Packets']]]
];
