var searchData=
[
  ['dairy_9335',['Dairy',['../classQuantConnect_1_1Securities_1_1Futures_1_1Dairy.html',1,'QuantConnect::Securities::Futures']]],
  ['darkcloudcover_9336',['DarkCloudCover',['../classQuantConnect_1_1Indicators_1_1CandlestickPatterns_1_1DarkCloudCover.html',1,'QuantConnect::Indicators::CandlestickPatterns']]],
  ['dataaggregatorinitializeparameters_9337',['DataAggregatorInitializeParameters',['../classQuantConnect_1_1Data_1_1DataAggregatorInitializeParameters.html',1,'QuantConnect::Data']]],
  ['dataagreement_9338',['DataAgreement',['../classQuantConnect_1_1Api_1_1DataAgreement.html',1,'QuantConnect::Api']]],
  ['datachannelprovider_9339',['DataChannelProvider',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1DataChannelProvider.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['dataconsolidator_9340',['DataConsolidator',['../classQuantConnect_1_1Data_1_1Consolidators_1_1DataConsolidator.html',1,'QuantConnect::Data::Consolidators']]],
  ['dataconsolidator_3c_20basedata_20_3e_9341',['DataConsolidator&lt; BaseData &gt;',['../classQuantConnect_1_1Data_1_1Consolidators_1_1DataConsolidator.html',1,'QuantConnect::Data::Consolidators']]],
  ['dataconsolidator_3c_20t_20_3e_9342',['DataConsolidator&lt; T &gt;',['../classQuantConnect_1_1Data_1_1Consolidators_1_1DataConsolidator.html',1,'QuantConnect::Data::Consolidators']]],
  ['dataconsolidatorpythonwrapper_9343',['DataConsolidatorPythonWrapper',['../classQuantConnect_1_1Python_1_1DataConsolidatorPythonWrapper.html',1,'QuantConnect::Python']]],
  ['datadictionary_9344',['DataDictionary',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20delisting_20_3e_9345',['DataDictionary&lt; Delisting &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20dividend_20_3e_9346',['DataDictionary&lt; Dividend &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20futureschain_20_3e_9347',['DataDictionary&lt; FuturesChain &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20futurescontract_20_3e_9348',['DataDictionary&lt; FuturesContract &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20margininterestrate_20_3e_9349',['DataDictionary&lt; MarginInterestRate &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20optionchain_20_3e_9350',['DataDictionary&lt; OptionChain &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20optioncontract_20_3e_9351',['DataDictionary&lt; OptionContract &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20quotebar_20_3e_9352',['DataDictionary&lt; QuoteBar &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20split_20_3e_9353',['DataDictionary&lt; Split &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20symbolchangedevent_20_3e_9354',['DataDictionary&lt; SymbolChangedEvent &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionary_3c_20tradebar_20_3e_9355',['DataDictionary&lt; TradeBar &gt;',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionary.html',1,'QuantConnect::Data::Market']]],
  ['datadictionaryextensions_9356',['DataDictionaryExtensions',['../classQuantConnect_1_1Data_1_1Market_1_1DataDictionaryExtensions.html',1,'QuantConnect::Data::Market']]],
  ['datadownloadconfig_9357',['DataDownloadConfig',['../structQuantConnect_1_1DownloaderDataProvider_1_1Launcher_1_1DataDownloadConfig.html',1,'QuantConnect::DownloaderDataProvider::Launcher']]],
  ['datadownloadergetparameters_9358',['DataDownloaderGetParameters',['../classQuantConnect_1_1DataDownloaderGetParameters.html',1,'QuantConnect']]],
  ['datafeedpacket_9359',['DataFeedPacket',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1DataFeedPacket.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['datahistory_9360',['DataHistory',['../classQuantConnect_1_1Data_1_1DataHistory.html',1,'QuantConnect::Data']]],
  ['datahistory_3c_20indicatordatapoints_20_3e_9361',['DataHistory&lt; IndicatorDataPoints &gt;',['../classQuantConnect_1_1Data_1_1DataHistory.html',1,'QuantConnect::Data']]],
  ['datahistory_3c_20slice_20_3e_9362',['DataHistory&lt; Slice &gt;',['../classQuantConnect_1_1Data_1_1DataHistory.html',1,'QuantConnect::Data']]],
  ['datalink_9363',['DataLink',['../classQuantConnect_1_1Api_1_1DataLink.html',1,'QuantConnect::Api']]],
  ['datalist_9364',['DataList',['../classQuantConnect_1_1Api_1_1DataList.html',1,'QuantConnect::Api']]],
  ['datamanager_9365',['DataManager',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1DataManager.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['datamonitor_9366',['DataMonitor',['../classQuantConnect_1_1Data_1_1DataMonitor.html',1,'QuantConnect::Data']]],
  ['datamonitorreport_9367',['DataMonitorReport',['../classQuantConnect_1_1DataMonitorReport.html',1,'QuantConnect']]],
  ['datapermissionmanager_9368',['DataPermissionManager',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1DataPermissionManager.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['datapriceslist_9369',['DataPricesList',['../classQuantConnect_1_1Api_1_1DataPricesList.html',1,'QuantConnect::Api']]],
  ['dataprocessor_9370',['DataProcessor',['../classQuantConnect_1_1ToolBox_1_1DataProcessor.html',1,'QuantConnect::ToolBox']]],
  ['dataprovidereventargs_9371',['DataProviderEventArgs',['../classQuantConnect_1_1DataProviderEventArgs.html',1,'QuantConnect']]],
  ['dataprovidernewdatarequesteventargs_9372',['DataProviderNewDataRequestEventArgs',['../classQuantConnect_1_1Interfaces_1_1DataProviderNewDataRequestEventArgs.html',1,'QuantConnect::Interfaces']]],
  ['dataqueuefutureschainuniversedatacollectionenumerator_9373',['DataQueueFuturesChainUniverseDataCollectionEnumerator',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Enumerators_1_1DataQueueFuturesChainUniverseDataCollectionEnumerator.html',1,'QuantConnect::Lean::Engine::DataFeeds::Enumerators']]],
  ['dataqueuehandlermanager_9374',['DataQueueHandlerManager',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1DataQueueHandlerManager.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['dataqueuehandlersubscriptionmanager_9375',['DataQueueHandlerSubscriptionManager',['../classQuantConnect_1_1Data_1_1DataQueueHandlerSubscriptionManager.html',1,'QuantConnect::Data']]],
  ['dataqueueoptionchainuniversedatacollectionenumerator_9376',['DataQueueOptionChainUniverseDataCollectionEnumerator',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Enumerators_1_1DataQueueOptionChainUniverseDataCollectionEnumerator.html',1,'QuantConnect::Lean::Engine::DataFeeds::Enumerators']]],
  ['dateformat_9377',['DateFormat',['../classQuantConnect_1_1DateFormat.html',1,'QuantConnect']]],
  ['daterules_9378',['DateRules',['../classQuantConnect_1_1Scheduling_1_1DateRules.html',1,'QuantConnect::Scheduling']]],
  ['datetimejsonconverter_9379',['DateTimeJsonConverter',['../classQuantConnect_1_1Util_1_1DateTimeJsonConverter.html',1,'QuantConnect::Util']]],
  ['datetimewithzone_9380',['DateTimeWithZone',['../structQuantConnect_1_1Time_1_1DateTimeWithZone.html',1,'QuantConnect::Time']]],
  ['daysininventory_9381',['DaysInInventory',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DaysInInventory.html',1,'QuantConnect::Data::Fundamental']]],
  ['daysinpayment_9382',['DaysInPayment',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DaysInPayment.html',1,'QuantConnect::Data::Fundamental']]],
  ['daysinsales_9383',['DaysInSales',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DaysInSales.html',1,'QuantConnect::Data::Fundamental']]],
  ['daytimeinforce_9384',['DayTimeInForce',['../classQuantConnect_1_1Orders_1_1TimeInForces_1_1DayTimeInForce.html',1,'QuantConnect::Orders::TimeInForces']]],
  ['ddacostofrevenueincomestatement_9385',['DDACostofRevenueIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DDACostofRevenueIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['debtduebeyondbalancesheet_9386',['DebtDueBeyondBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DebtDueBeyondBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['debtdueinyear1balancesheet_9387',['DebtDueInYear1BalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DebtDueInYear1BalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['debtdueinyear2balancesheet_9388',['DebtDueInYear2BalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DebtDueInYear2BalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['debtdueinyear5balancesheet_9389',['DebtDueInYear5BalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DebtDueInYear5BalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['debtsecuritiesbalancesheet_9390',['DebtSecuritiesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DebtSecuritiesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['debtsecuritiesinissuebalancesheet_9391',['DebtSecuritiesinIssueBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DebtSecuritiesinIssueBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['debttoassets_9392',['DebtToAssets',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DebtToAssets.html',1,'QuantConnect::Data::Fundamental']]],
  ['debttotalbalancesheet_9393',['DebtTotalBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DebtTotalBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['debuggerhelper_9394',['DebuggerHelper',['../classQuantConnect_1_1AlgorithmFactory_1_1DebuggerHelper.html',1,'QuantConnect::AlgorithmFactory']]],
  ['debugpacket_9395',['DebugPacket',['../classQuantConnect_1_1Packets_1_1DebugPacket.html',1,'QuantConnect::Packets']]],
  ['decreaseininterestbearingdepositsinbankcashflowstatement_9396',['DecreaseInInterestBearingDepositsInBankCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DecreaseInInterestBearingDepositsInBankCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['deedleutil_9397',['DeedleUtil',['../classQuantConnect_1_1Report_1_1DeedleUtil.html',1,'QuantConnect::Report']]],
  ['defaultbrokeragemessagehandler_9398',['DefaultBrokerageMessageHandler',['../classQuantConnect_1_1Brokerages_1_1DefaultBrokerageMessageHandler.html',1,'QuantConnect.Brokerages.DefaultBrokerageMessageHandler'],['../classQuantConnect_1_1Messages_1_1DefaultBrokerageMessageHandler.html',1,'QuantConnect.Messages.DefaultBrokerageMessageHandler']]],
  ['defaultbrokeragemodel_9399',['DefaultBrokerageModel',['../classQuantConnect_1_1Brokerages_1_1DefaultBrokerageModel.html',1,'QuantConnect.Brokerages.DefaultBrokerageModel'],['../classQuantConnect_1_1Messages_1_1DefaultBrokerageModel.html',1,'QuantConnect.Messages.DefaultBrokerageModel']]],
  ['defaultconnectionhandler_9400',['DefaultConnectionHandler',['../classQuantConnect_1_1Brokerages_1_1DefaultConnectionHandler.html',1,'QuantConnect::Brokerages']]],
  ['defaultconverter_9401',['DefaultConverter',['../classQuantConnect_1_1DefaultConverter.html',1,'QuantConnect']]],
  ['defaultdataprovider_9402',['DefaultDataProvider',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1DefaultDataProvider.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['defaultexercisemodel_9403',['DefaultExerciseModel',['../classQuantConnect_1_1Messages_1_1DefaultExerciseModel.html',1,'QuantConnect.Messages.DefaultExerciseModel'],['../classQuantConnect_1_1Orders_1_1OptionExercise_1_1DefaultExerciseModel.html',1,'QuantConnect.Orders.OptionExercise.DefaultExerciseModel']]],
  ['defaultmargincallmodel_9404',['DefaultMarginCallModel',['../classQuantConnect_1_1Messages_1_1DefaultMarginCallModel.html',1,'QuantConnect.Messages.DefaultMarginCallModel'],['../classQuantConnect_1_1Securities_1_1DefaultMarginCallModel.html',1,'QuantConnect.Securities.DefaultMarginCallModel']]],
  ['defaultoptionassignmentmodel_9405',['DefaultOptionAssignmentModel',['../classQuantConnect_1_1Securities_1_1Option_1_1DefaultOptionAssignmentModel.html',1,'QuantConnect::Securities::Option']]],
  ['defaultoptionpositioncollectionenumerator_9406',['DefaultOptionPositionCollectionEnumerator',['../classQuantConnect_1_1Securities_1_1Option_1_1StrategyMatcher_1_1DefaultOptionPositionCollectionEnumerator.html',1,'QuantConnect::Securities::Option::StrategyMatcher']]],
  ['defaultorderbook_9407',['DefaultOrderBook',['../classQuantConnect_1_1Brokerages_1_1DefaultOrderBook.html',1,'QuantConnect::Brokerages']]],
  ['defaultsymbolgenerator_9408',['DefaultSymbolGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1DefaultSymbolGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['deferredassetsbalancesheet_9409',['DeferredAssetsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DeferredAssetsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['deferredcostsbalancesheet_9410',['DeferredCostsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DeferredCostsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['deferredincometaxcashflowstatement_9411',['DeferredIncomeTaxCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DeferredIncomeTaxCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['deferredincometotalbalancesheet_9412',['DeferredIncomeTotalBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DeferredIncomeTotalBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['deferredpolicyacquisitioncostsbalancesheet_9413',['DeferredPolicyAcquisitionCostsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DeferredPolicyAcquisitionCostsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['deferredtaxassetsbalancesheet_9414',['DeferredTaxAssetsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DeferredTaxAssetsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['deferredtaxcashflowstatement_9415',['DeferredTaxCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DeferredTaxCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['deferredtaxliabilitiestotalbalancesheet_9416',['DeferredTaxLiabilitiesTotalBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DeferredTaxLiabilitiesTotalBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['definedpensionbenefitbalancesheet_9417',['DefinedPensionBenefitBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DefinedPensionBenefitBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['delay_9418',['Delay',['../classQuantConnect_1_1Indicators_1_1Delay.html',1,'QuantConnect::Indicators']]],
  ['delayedsettlementmodel_9419',['DelayedSettlementModel',['../classQuantConnect_1_1Securities_1_1DelayedSettlementModel.html',1,'QuantConnect::Securities']]],
  ['delisting_9420',['Delisting',['../classQuantConnect_1_1Data_1_1Market_1_1Delisting.html',1,'QuantConnect::Data::Market']]],
  ['delistingeventprovider_9421',['DelistingEventProvider',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Enumerators_1_1DelistingEventProvider.html',1,'QuantConnect::Lean::Engine::DataFeeds::Enumerators']]],
  ['delistingnotificationeventargs_9422',['DelistingNotificationEventArgs',['../classQuantConnect_1_1Brokerages_1_1DelistingNotificationEventArgs.html',1,'QuantConnect::Brokerages']]],
  ['delistings_9423',['Delistings',['../classQuantConnect_1_1Data_1_1Market_1_1Delistings.html',1,'QuantConnect::Data::Market']]],
  ['delta_9424',['Delta',['../classQuantConnect_1_1Indicators_1_1Delta.html',1,'QuantConnect::Indicators']]],
  ['demarkerindicator_9425',['DeMarkerIndicator',['../classQuantConnect_1_1Indicators_1_1DeMarkerIndicator.html',1,'QuantConnect::Indicators']]],
  ['depletioncashflowstatement_9426',['DepletionCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepletionCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['depletionincomestatement_9427',['DepletionIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepletionIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['depositcertificatesbalancesheet_9428',['DepositCertificatesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepositCertificatesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['depositsbybankbalancesheet_9429',['DepositsbyBankBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepositsbyBankBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['depositsmadeunderassumedreinsurancecontractbalancesheet_9430',['DepositsMadeunderAssumedReinsuranceContractBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepositsMadeunderAssumedReinsuranceContractBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['depositsreceivedundercededinsurancecontractbalancesheet_9431',['DepositsReceivedunderCededInsuranceContractBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepositsReceivedunderCededInsuranceContractBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['depreciationamortizationdepletioncashflowstatement_9432',['DepreciationAmortizationDepletionCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepreciationAmortizationDepletionCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['depreciationamortizationdepletionincomestatement_9433',['DepreciationAmortizationDepletionIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepreciationAmortizationDepletionIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['depreciationandamortizationcashflowstatement_9434',['DepreciationAndAmortizationCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepreciationAndAmortizationCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['depreciationandamortizationincomestatement_9435',['DepreciationAndAmortizationIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepreciationAndAmortizationIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['depreciationcashflowstatement_9436',['DepreciationCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepreciationCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['depreciationincomestatement_9437',['DepreciationIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepreciationIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['depreciationsupplementalincomestatement_9438',['DepreciationSupplementalIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DepreciationSupplementalIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['derivativeassetsbalancesheet_9439',['DerivativeAssetsBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DerivativeAssetsBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['derivativeoscillator_9440',['DerivativeOscillator',['../classQuantConnect_1_1Indicators_1_1DerivativeOscillator.html',1,'QuantConnect::Indicators']]],
  ['derivativeproductliabilitiesbalancesheet_9441',['DerivativeProductLiabilitiesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DerivativeProductLiabilitiesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['descendingbylegcountoptionstrategydefinitionenumerator_9442',['DescendingByLegCountOptionStrategyDefinitionEnumerator',['../classQuantConnect_1_1Securities_1_1Option_1_1StrategyMatcher_1_1DescendingByLegCountOptionStrategyDefinitionEnumerator.html',1,'QuantConnect::Securities::Option::StrategyMatcher']]],
  ['detrendedpriceoscillator_9443',['DetrendedPriceOscillator',['../classQuantConnect_1_1Indicators_1_1DetrendedPriceOscillator.html',1,'QuantConnect::Indicators']]],
  ['dilutedaccountingchange_9444',['DilutedAccountingChange',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DilutedAccountingChange.html',1,'QuantConnect::Data::Fundamental']]],
  ['dilutedaverageshares_9445',['DilutedAverageShares',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DilutedAverageShares.html',1,'QuantConnect::Data::Fundamental']]],
  ['dilutedcontepsgrowth_9446',['DilutedContEPSGrowth',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DilutedContEPSGrowth.html',1,'QuantConnect::Data::Fundamental']]],
  ['dilutedcontinuousoperations_9447',['DilutedContinuousOperations',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DilutedContinuousOperations.html',1,'QuantConnect::Data::Fundamental']]],
  ['diluteddiscontinuousoperations_9448',['DilutedDiscontinuousOperations',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DilutedDiscontinuousOperations.html',1,'QuantConnect::Data::Fundamental']]],
  ['dilutedeps_9449',['DilutedEPS',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DilutedEPS.html',1,'QuantConnect::Data::Fundamental']]],
  ['dilutedepsgrowth_9450',['DilutedEPSGrowth',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DilutedEPSGrowth.html',1,'QuantConnect::Data::Fundamental']]],
  ['dilutedepsothergainslosses_9451',['DilutedEPSOtherGainsLosses',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DilutedEPSOtherGainsLosses.html',1,'QuantConnect::Data::Fundamental']]],
  ['dilutedextraordinary_9452',['DilutedExtraordinary',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DilutedExtraordinary.html',1,'QuantConnect::Data::Fundamental']]],
  ['dilutedniavailtocomstockholdersincomestatement_9453',['DilutedNIAvailtoComStockholdersIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DilutedNIAvailtoComStockholdersIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['diskdatacacheprovider_9454',['DiskDataCacheProvider',['../classQuantConnect_1_1Data_1_1DiskDataCacheProvider.html',1,'QuantConnect::Data']]],
  ['disposableextensions_9455',['DisposableExtensions',['../classQuantConnect_1_1Util_1_1DisposableExtensions.html',1,'QuantConnect::Util']]],
  ['dividend_9456',['Dividend',['../classQuantConnect_1_1Data_1_1Market_1_1Dividend.html',1,'QuantConnect::Data::Market']]],
  ['dividendcoverageratio_9457',['DividendCoverageRatio',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DividendCoverageRatio.html',1,'QuantConnect::Data::Fundamental']]],
  ['dividendeventprovider_9458',['DividendEventProvider',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1Enumerators_1_1DividendEventProvider.html',1,'QuantConnect::Lean::Engine::DataFeeds::Enumerators']]],
  ['dividendincomeincomestatement_9459',['DividendIncomeIncomeStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DividendIncomeIncomeStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['dividendpaidcfocashflowstatement_9460',['DividendPaidCFOCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DividendPaidCFOCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['dividendpershare_9461',['DividendPerShare',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DividendPerShare.html',1,'QuantConnect::Data::Fundamental']]],
  ['dividendreceivedcfocashflowstatement_9462',['DividendReceivedCFOCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DividendReceivedCFOCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['dividends_9463',['Dividends',['../classQuantConnect_1_1Data_1_1Market_1_1Dividends.html',1,'QuantConnect::Data::Market']]],
  ['dividendspaiddirectcashflowstatement_9464',['DividendsPaidDirectCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DividendsPaidDirectCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['dividendspayablebalancesheet_9465',['DividendsPayableBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DividendsPayableBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['dividendsplitmapgenerator_9466',['DividendSplitMapGenerator',['../classQuantConnect_1_1ToolBox_1_1RandomDataGenerator_1_1DividendSplitMapGenerator.html',1,'QuantConnect::ToolBox::RandomDataGenerator']]],
  ['dividendsreceivedcficashflowstatement_9467',['DividendsReceivedCFICashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DividendsReceivedCFICashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['dividendsreceiveddirectcashflowstatement_9468',['DividendsReceivedDirectCashFlowStatement',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DividendsReceivedDirectCashFlowStatement.html',1,'QuantConnect::Data::Fundamental']]],
  ['dividendyieldmodelpythonwrapper_9469',['DividendYieldModelPythonWrapper',['../classQuantConnect_1_1Python_1_1DividendYieldModelPythonWrapper.html',1,'QuantConnect::Python']]],
  ['dividendyieldprovider_9470',['DividendYieldProvider',['../classQuantConnect_1_1Data_1_1DividendYieldProvider.html',1,'QuantConnect::Data']]],
  ['dllnotfoundpythonexceptioninterpreter_9471',['DllNotFoundPythonExceptionInterpreter',['../classQuantConnect_1_1Exceptions_1_1DllNotFoundPythonExceptionInterpreter.html',1,'QuantConnect.Exceptions.DllNotFoundPythonExceptionInterpreter'],['../classQuantConnect_1_1Messages_1_1DllNotFoundPythonExceptionInterpreter.html',1,'QuantConnect.Messages.DllNotFoundPythonExceptionInterpreter']]],
  ['documentationattribute_9472',['DocumentationAttribute',['../classQuantConnect_1_1DocumentationAttribute.html',1,'QuantConnect']]],
  ['doji_9473',['Doji',['../classQuantConnect_1_1Indicators_1_1CandlestickPatterns_1_1Doji.html',1,'QuantConnect::Indicators::CandlestickPatterns']]],
  ['dojistar_9474',['DojiStar',['../classQuantConnect_1_1Indicators_1_1CandlestickPatterns_1_1DojiStar.html',1,'QuantConnect::Indicators::CandlestickPatterns']]],
  ['dollarvolumeuniversedefinitions_9475',['DollarVolumeUniverseDefinitions',['../classQuantConnect_1_1Algorithm_1_1DollarVolumeUniverseDefinitions.html',1,'QuantConnect::Algorithm']]],
  ['donchianchannel_9476',['DonchianChannel',['../classQuantConnect_1_1Indicators_1_1DonchianChannel.html',1,'QuantConnect::Indicators']]],
  ['doubleexponentialmovingaverage_9477',['DoubleExponentialMovingAverage',['../classQuantConnect_1_1Indicators_1_1DoubleExponentialMovingAverage.html',1,'QuantConnect::Indicators']]],
  ['doubleunixsecondsdatetimejsonconverter_9478',['DoubleUnixSecondsDateTimeJsonConverter',['../classQuantConnect_1_1Util_1_1DoubleUnixSecondsDateTimeJsonConverter.html',1,'QuantConnect::Util']]],
  ['downgradeerrorcodetowarningbrokeragemessagehandler_9479',['DowngradeErrorCodeToWarningBrokerageMessageHandler',['../classQuantConnect_1_1Brokerages_1_1DowngradeErrorCodeToWarningBrokerageMessageHandler.html',1,'QuantConnect::Brokerages']]],
  ['downloadercommandarguments_9480',['DownloaderCommandArguments',['../classQuantConnect_1_1DownloaderDataProvider_1_1Launcher_1_1Models_1_1Constants_1_1DownloaderCommandArguments.html',1,'QuantConnect::DownloaderDataProvider::Launcher::Models::Constants']]],
  ['downloaderdataprovider_9481',['DownloaderDataProvider',['../classQuantConnect_1_1Lean_1_1Engine_1_1DataFeeds_1_1DownloaderDataProvider.html',1,'QuantConnect::Lean::Engine::DataFeeds']]],
  ['downloaderdataproviderargumentparser_9482',['DownloaderDataProviderArgumentParser',['../classDownloaderDataProviderArgumentParser.html',1,'']]],
  ['downloaderextensions_9483',['DownloaderExtensions',['../classQuantConnect_1_1Data_1_1DownloaderExtensions.html',1,'QuantConnect::Data']]],
  ['downloadfailedeventargs_9484',['DownloadFailedEventArgs',['../classQuantConnect_1_1DownloadFailedEventArgs.html',1,'QuantConnect']]],
  ['dpsgrowth_9485',['DPSGrowth',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DPSGrowth.html',1,'QuantConnect::Data::Fundamental']]],
  ['dragonflydoji_9486',['DragonflyDoji',['../classQuantConnect_1_1Indicators_1_1CandlestickPatterns_1_1DragonflyDoji.html',1,'QuantConnect::Indicators::CandlestickPatterns']]],
  ['drawdowncollection_9487',['DrawdownCollection',['../classQuantConnect_1_1Report_1_1DrawdownCollection.html',1,'QuantConnect::Report']]],
  ['drawdownperiod_9488',['DrawdownPeriod',['../classQuantConnect_1_1Report_1_1DrawdownPeriod.html',1,'QuantConnect::Report']]],
  ['dualsymbolindicator_9489',['DualSymbolIndicator',['../classQuantConnect_1_1Indicators_1_1DualSymbolIndicator.html',1,'QuantConnect::Indicators']]],
  ['dualsymbolindicator_3c_20decimal_20_3e_9490',['DualSymbolIndicator&lt; decimal &gt;',['../classQuantConnect_1_1Indicators_1_1DualSymbolIndicator.html',1,'QuantConnect::Indicators']]],
  ['dualsymbolindicator_3c_20double_20_3e_9491',['DualSymbolIndicator&lt; double &gt;',['../classQuantConnect_1_1Indicators_1_1DualSymbolIndicator.html',1,'QuantConnect::Indicators']]],
  ['duefromrelatedpartiesbalancesheet_9492',['DueFromRelatedPartiesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DueFromRelatedPartiesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['duefromrelatedpartiescurrentbalancesheet_9493',['DuefromRelatedPartiesCurrentBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DuefromRelatedPartiesCurrentBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['duefromrelatedpartiesnoncurrentbalancesheet_9494',['DuefromRelatedPartiesNonCurrentBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DuefromRelatedPartiesNonCurrentBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['duetorelatedpartiesbalancesheet_9495',['DuetoRelatedPartiesBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DuetoRelatedPartiesBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['duetorelatedpartiescurrentbalancesheet_9496',['DuetoRelatedPartiesCurrentBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DuetoRelatedPartiesCurrentBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['duetorelatedpartiesnoncurrentbalancesheet_9497',['DuetoRelatedPartiesNonCurrentBalanceSheet',['../classQuantConnect_1_1Data_1_1Fundamental_1_1DuetoRelatedPartiesNonCurrentBalanceSheet.html',1,'QuantConnect::Data::Fundamental']]],
  ['dynamicdata_9498',['DynamicData',['../classQuantConnect_1_1Data_1_1DynamicData.html',1,'QuantConnect::Data']]],
  ['dynamicdataconsolidator_9499',['DynamicDataConsolidator',['../classQuantConnect_1_1Data_1_1Consolidators_1_1DynamicDataConsolidator.html',1,'QuantConnect::Data::Consolidators']]],
  ['dynamicsecuritydata_9500',['DynamicSecurityData',['../classQuantConnect_1_1Messages_1_1DynamicSecurityData.html',1,'QuantConnect.Messages.DynamicSecurityData'],['../classQuantConnect_1_1Securities_1_1DynamicSecurityData.html',1,'QuantConnect.Securities.DynamicSecurityData']]]
];
